"""
Convert GEOM drugs_featurized.msgpack to SDF using SMILES + RDKit ETKDG 3D.

Bond types come from the msgpack (ground truth).
3D coordinates are generated by RDKit ETKDG.

Usage:
    python scripts/geom_featurized_to_sdf.py \
        --input data/drugs_featurized.msgpack.tar.gz \
        --output data/geom_drugs.sdf \
        --max_mols 200000
"""

import argparse, sys, time, tarfile, msgpack
from pathlib import Path


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--input', required=True)
    p.add_argument('--output', required=True)
    p.add_argument('--max_mols', type=int, default=None)
    p.add_argument('--seed', type=int, default=42)
    return p.parse_args()


_BOND_TYPE_MAP = {
    'single':   None,   # filled after import
    'double':   None,
    'triple':   None,
    'aromatic': None,
}


def smiles_to_3d_mol(smiles: str, seed: int = 42):
    """Build RDKit mol from SMILES with ETKDG 3D conformer."""
    from rdkit import Chem
    from rdkit.Chem import AllChem

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    try:
        Chem.SanitizeMol(mol)
    except Exception:
        return None

    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = seed
    ret = AllChem.EmbedMolecule(mol, params)
    if ret != 0:
        # Fallback: distance geometry
        ret = AllChem.EmbedMolecule(mol, AllChem.ETDG())
    if ret != 0:
        return None

    try:
        AllChem.MMFFOptimizeMolecule(mol)
    except Exception:
        pass

    return mol


def main():
    args = parse_args()

    from rdkit import Chem
    from rdkit.Chem import BondType
    _BOND_TYPE_MAP['single'] = BondType.SINGLE
    _BOND_TYPE_MAP['double'] = BondType.DOUBLE
    _BOND_TYPE_MAP['triple'] = BondType.TRIPLE
    _BOND_TYPE_MAP['aromatic'] = BondType.AROMATIC

    print(f"Opening: {args.input}")
    with tarfile.open(args.input, 'r:gz') as tar:
        member = tar.getmembers()[0]
        print(f"  Member: {member.name}  ({member.size / 1e9:.1f} GB)")
        f = tar.extractfile(member)
        unpacker = msgpack.Unpacker(f, raw=False, strict_map_key=False, max_buffer_size=0)

        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        writer = Chem.SDWriter(str(out_path))

        n_written = n_failed = n_total = 0
        t0 = time.time()

        for chunk in unpacker:
            if not isinstance(chunk, dict):
                continue
            items = list(chunk.items())
            if args.max_mols:
                remaining = args.max_mols - n_written
                items = items[:remaining]

            for smiles, conformers in items:
                n_total += 1
                if n_total % 10000 == 0:
                    elapsed = time.time() - t0
                    print(f"  {n_total} processed | {n_written} written | "
                          f"{n_failed} failed | {n_total/elapsed:.0f} mol/s")

                mol = smiles_to_3d_mol(smiles, seed=args.seed)
                if mol is None:
                    n_failed += 1
                    continue

                writer.write(mol)
                n_written += 1

                if args.max_mols and n_written >= args.max_mols:
                    break

            if args.max_mols and n_written >= args.max_mols:
                break

    writer.close()
    elapsed = time.time() - t0
    size_mb = out_path.stat().st_size / 1e6
    print(f"\nDone: {n_written} written, {n_failed} failed in {elapsed:.0f}s")
    print(f"Output: {out_path} ({size_mb:.0f} MB)")


if __name__ == '__main__':
    main()
